// src/pages/Projects.jsx
import React from 'react';
import ProjectCard from '../components/ProjectCard'; 

const Projects = () => {
  return (
    <div className="page-container">
      <h1>AI Projects</h1>
      
      {/* --- HONOURS PROJECT SHOWCASE --- */}
      <div className="main-project-showcase">
        <h2>Honours Project: AI-Powered Personality Detection Chatbot</h2>
        <p>This project represents the culmination of my undergraduate studies, combining my interests in Natural Language Processing, complex system architecture, and the practical application of AI to understand human nuances.</p>
        
        <div className="project-images">
            <img src="/B.1-High-Level-Architecture.png" alt="High-Level Architecture Diagram" />
            <img src="/B.2-Component-Interaction.png" alt="Component Interaction Diagram" />
        </div>
        <p className="image-caption"><em>Key architecture diagrams from the project report.</em></p>

        <h3>The Challenge: Moving Beyond Static Questionnaires</h3>
        <p>Traditional personality assessments like the Myers-Briggs Type Indicator (MBTI) are widely used but suffer from well-known limitations. They rely on static, multiple-choice questions that can feel rigid, fail to capture the context of real-life situations, and are vulnerable to response biases.</p>
        <p>The core problem this project addressed was: <strong>Can a conversational AI provide a richer, more nuanced, and potentially less biased exploration of personality preferences compared to traditional methods?</strong></p>

        <h3>My Solution: A Modular, Privacy-First Conversational AI</h3>
        <p>I engineered a sophisticated chatbot prototype from the ground up to explore a user's personality through interactive, open-ended dialogue. The system was designed to engage users naturally, ask personalised questions, and handle ambiguity in a way that static forms cannot.</p>
        <p>A primary technical and ethical consideration was <strong>data privacy</strong>. To ensure all user data remained secure, the entire system was architected to run locally, using the <strong>Ollama</strong> runtime to serve a fine-tuned <strong>Mistral 7B Large Language Model (LLM)</strong> without sending any conversational data to third-party APIs.</p>

        <h3>Key Architectural Features</h3>
        <ul>
          <li><strong>Modular Facade-Based Controller:</strong> The system's core was a central controller that orchestrated interactions between distinct, specialised components for state management, question selection, message handling, and response generation.</li>
          <li><strong>Context-Aware Personalisation:</strong> The chatbot used details from the user's background and recent conversation topics to tailor questions, making the interaction feel more relevant and engaging.</li>
          <li><strong>Intelligent Ambiguity Handling:</strong> When a user gave a nuanced answer like "it depends," the system detected this and deployed a "tendency probe"—a specific follow-up question to gently ask for their most common leaning.</li>
          <li><strong>Pragmatic Hybrid AI Model:</strong> In response to the unreliability of the 7B LLM for precise analytical tasks, I re-architected the system to use the LLM for generation while implementing critical scoring logic as a stable and predictable keyword-based heuristic engine in Python.</li>
          <li><strong>Dual Summary Mechanism:</strong> Upon completion, the chatbot provided two distinct perspectives: a "Controlled Summary" based on the calculated scores and an "Organic Summary" generated by the LLM based on its holistic interpretation of the conversation.</li>
        </ul>
        
        <h3>Tech Stack</h3>
        <p><strong>Language:</strong> Python | <strong>AI/ML Frameworks:</strong> LangChain, Unsloth | <strong>LLM & Runtime:</strong> Mistral 7B, Ollama | <strong>Frontend:</strong> Streamlit | <strong>Core Libraries:</strong> Pandas, PyTest</p>

        <h3>Key Challenges & Learnings</h3>
        <p>The journey of building this prototype was a significant learning experience in practical AI engineering. The biggest challenge was the inconsistency of the 7B parameter model for analytical tasks, which led to a critical learning: <strong>knowing when to pivot</strong>. I made the conscious decision to replace the unreliable LLM-based scoring with a deterministic Python-based keyword system. This improved stability immensely and taught me the importance of using the right tool for the job.</p>

        <h3>Relevance to Storm ID</h3>
        <p>This project aligns directly with Storm ID's focus on applying AI to solve complex, real-world problems. My experience in building a system that understands nuanced human language is applicable to their work in **Case Triage** and **Complaints Handling**. The chatbot's architecture is a foundational concept within **Agentic Workflows**, and my privacy-first, pragmatic approach to development demonstrates the ethical and stable engineering practices valued by Storm ID.</p>
      </div>

      <hr className="section-divider" />

     {/* --- OTHER KEY PROJECTS --- */}
      <h2>Other Key Projects</h2>
      <div className="other-projects">
        <ProjectCard
          title="Machine Learning for Predictive Healthcare"
          description="Developed and validated a Random Forest classification model to predict the likelihood of a patient having a stroke based on clinical features. The project involved comprehensive data preprocessing, feature engineering (e.g., age-squared transformations, BMI-glucose interactions), and rigorous cross-validation. The final model achieved 91% overall accuracy and an AUC of 0.83."
          techStack="Python, Pandas, Scikit-learn, Matplotlib"
          relevance="This project is directly relevant to Storm ID's award-winning work with NHS Scotland. It demonstrates my ability to work with healthcare data and build the exact type of predictive models used to improve patient outcomes."
          imageUrl="/ml-roc-curve.png" // ADD THIS LINE
          imageAlt="ROC Curve for Stroke Prediction Model" // AND THIS LINE
       />
        <ProjectCard
          title="Integrated Group Project: PT Connect Fitness App"
          description="As the dedicated Web Developer in a six-person team, I was responsible for building the web application for 'PT Connect'—a management suite for personal trainers. The application featured a client dashboard, session scheduling, and analytics visualization."
          techStack="React, JavaScript, HTML/CSS, Chart.js, Firebase"
          relevance="Demonstrates direct, hands-on experience developing with React, the primary front-end technology used at Storm ID. It showcases my ability to work collaboratively in a team to deliver a functional web product."
          imageUrl="/aadp-deployment-view.png" // ADD THIS LINE
          imageAlt="Deployment View Diagram for E-Commerce System" // AND THIS LINE
        />
        <ProjectCard
          title="Application Architecture & Design Patterns"
          description="Led the design of a scalable e-commerce information management system for a premium whiskey company. The architecture incorporated multiple design patterns, including a three-tier Layered Architecture, Model-View-Controller (MVC) for the presentation layer, and an Event-Driven Architecture to handle asynchronous processes like order fulfillment and invoicing."
          techStack="System Design, Architectural Diagrams (UML), MVC, Event-Driven Architecture"
          relevance="This project demonstrates a strong understanding of how to design robust, scalable, and maintainable software systems—a critical skill for any engineering role at Storm ID, where building enterprise-grade platforms is key."
          imageUrl="/ip3-mvc-diagram.png" // ADD THIS LINE
          imageAlt="MVC Diagram for PT Connect Web and Mobile App" // AND THIS LINE       
        />
      </div>
    </div>
  );
};

export default Projects;